import type { InventoryItemId } from '@/game/core/types';

export const inventoryItemLabels = {
  'copper-ore': '铜矿',
  'iron-ore': '铁矿',
  'silver-ore': '银矿',
  'copper-ore-1-star': '铜矿 1★',
  'copper-ore-2-star': '铜矿 2★',
  'copper-ore-3-star': '铜矿 3★',
  'iron-ore-1-star': '铁矿 1★',
  'iron-ore-2-star': '铁矿 2★',
  'iron-ore-3-star': '铁矿 3★',
  'silver-ore-1-star': '银矿 1★',
  'silver-ore-2-star': '银矿 2★',
  'silver-ore-3-star': '银矿 3★',
  sunleaf: '日叶草',
  moonbell: '月铃草',
  'recruit-ticket': '招募券',
  'adamant-hammer-1-star': '精金锤 1★',
  'adamant-hammer-2-star': '精金锤 2★',
  'adamant-hammer-3-star': '精金锤 3★',
  'premium-plate': '氪金板',
  'rune-dust': '符文尘',
  'ember-shard': '余烬碎片',
  'frost-core': '霜核',
  'astral-fragment': '星界碎片',
  'recipe-ember-tonic-placeholder': '配方占位：余烬药剂',
  'recipe-frostguard-placeholder': '配方占位：霜卫药剂',
  'recipe-astral-tea-placeholder': '配方占位：星界茶',
  'equipment-ember-hollow-placeholder': '装备占位：谷地遗物',
  'equipment-frostmarch-placeholder': '装备占位：霜临遗物',
  'equipment-astral-rift-placeholder': '装备占位：星界遗物',
} as const satisfies Record<InventoryItemId, string>;
